CRITERION_DEFINES_COMMON = [
    "HAVE_BAZEL_BUILD=1",
    "ENABLE_NLS=0",
    "ENABLE_VALGRIND_ERRORS=0",
    "HAVE_CLOCK_GETTIME=1",
    "HAVE_CLOCK_MONOTONIC_RAW=1",
    "HAVE_FOPENCOOKIE=1",
    "HAVE_FUNOPEN=1",
    "HAVE_GETCWD=1",
    "HAVE_ISATTY=1",
    "HAVE_NL_LANG_INFO=1",
    "HAVE_OPEN_MEMSTREAM=1",
    "HAVE_STRTOK_R=1",
    "HAVE_STRTOK_S=1",
    "NN_H=1",
    "NN_REQREP_H=1",
]

CRITERION_DEFINES_UNIX = CRITERION_DEFINES_COMMON + [
    "HAVE_PTHREADS=1",
    # "HAVE_WIN32_GETCURRENTDIRECTORY=0",
    # "HAVE_WIN32_PATHISRELATIVE=0",
    # "HAVE_WIN32_SYNCHAPI=0",
    # "HAVE_WIN32_THREADS=0",
    'NN_SOCKET_PATH="/tmp/"',
]

CRITERION_DEFINES_WINDOWS = CRITERION_DEFINES_COMMON + [
    # "MINGW_DEFINE_OFF_T=0",
    "HAVE_WIN32_GETCURRENTDIRECTORY=1",
    "HAVE_WIN32_PATHISRELATIVE=1",
    "HAVE_WIN32_SYNCHAPI=1",
    "HAVE_WIN32_THREADS=1",
    'NN_SOCKET_PATH=""',
]
